### ISSUE TITLE
Add multiple file Support in a one link

### ISSUE THREAD

**Issue by shiva20991** [AbirHasan2005/PyroFilesStoreBot#13]
Multiple files in a one link

**Comment by shiva20991** [comment]
Want to batch multiple file in a single link..now it's generating link for each file. For example I want to save 100files in a single link..if I click a link 100 files want to fetch.can able to understand ah bro

**Comment by AbirHasan2005** [comment]
Okay, I will try to do that.

Thanks for suggestion.

**Comment by shiva20991** [comment]
Waiting for it bro..TQ for it bro

**Comment by AbirHasan2005** [comment]
> https://www.infotelbot.com/2021/05/how-to-make-telegram-file-link-share-bot.html
> 
> like this one it has batch support.. just posting for reference purpose

@sunilroy007 That's in base64 encrypted. You want like that??

**Comment by shiva20991** [comment]
No bro .just add a feature like that bro.. waiting for it bro...

**Comment by sunilroy007** [comment]
> > https://www.infotelbot.com/2021/05/how-to-make-telegram-file-link-share-bot.html
> > like this one it has batch support.. just posting for reference purpose
> 
> @sunilroy007 That's in base64 encrypted. You want like that??

Dont know whats that 64 lol,just posted for reference  bro.. give us  whats suit you  :)

**Comment by AbirHasan2005** [comment]
Okay

**Comment by shiva20991** [comment]
> Okay



> Okay

Bro when will this feature will be update

**Comment by AbirHasan2005** [comment]
Added this feature.
