### ISSUE TITLE
User Ban is not working

### ISSUE THREAD

**Issue by Naviya2** [AbirHasan2005/PyroFilesStoreBot#21]
User ban is not checking on start after banning .. please fix it....

**Comment by AbirHasan2005** [comment]
First Tell,
Banned where??
In Updates Channel or BANNED_USERS Config or Database??

**Comment by Naviya2** [comment]
Banned users

> First Tell,
> Banned where??
> In Updates Channel or BANNED_USERS Config or Database??

BANNED_USERS

**Comment by Naviya2** [comment]
If i banned a user. it is sending the banning info to the user but it is'nt checking the user at startup after banning. the banned user can freely use the bot

**Comment by AbirHasan2005** [comment]
Are you using latest one??

**Comment by Naviya2** [comment]
> Are you using latest one??

yes i have deployed your bot and tested yesterday but it isnt working
