### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by shiva20991** [AbirHasan2005/PyroFilesStoreBot#22]
![Screenshot_20210813-065951](https://user-images.githubusercontent.com/80451254/129292070-f4b0cd54-eb18-4ec1-b0ea-5a66b8c86247.png)

There is issue bro

**Comment by FayasNoushad** [comment]
Your log channel is private now. Change visibility that channel to public.

**Comment by AbirHasan2005** [comment]
Fixed 😅
