### ISSUE TITLE
Peer id invaild

### ISSUE THREAD

**Issue by Abhishek8r456** [AbirHasan2005/PyroFilesStoreBot#25]
![Screenshot_20210920-210452_Chrome](https://user-images.githubusercontent.com/67840255/134030407-e66aba53-736e-4707-b461-1e81edd311e4.jpg)

Getting this error in heroku application log when I start my bot in telegram.

**Comment by AbirHasan2005** [comment]
Add bot in Channels as admin else it can't find via chat_id!
