### ISSUE TITLE
please help me sir..

### ISSUE THREAD

**Issue by sasangeo** [AbirHasan2005/PyroFilesStoreBot#26]
i have problem when deploying to railway.app "python3: can't open file 'bot.py': [Errno 2] No such file or directory "Is there an explanation?

**Comment by AbirHasan2005** [comment]
Can you get build logs?

**Comment by gitlover66** [comment]
![Uploading IMG_20211122_102047.jpg…]()

**Comment by gitlover66** [comment]
> Can you get build logs?

![IMG_20211122_102047](https://user-images.githubusercontent.com/88269383/142802943-ff75351e-94fb-478a-9e47-b6b570a4b075.jpg)

**Comment by AbirHasan2005** [comment]
Now check, hope works.
