### ISSUE TITLE
Auth Users

### ISSUE THREAD

**Issue by rahulrahamanx** [AbirHasan2005/PyroFilesStoreBot#29]
Please Add AUTH USER permission so user cannot get shareable link but they can get files from Link..
Some times users send files to the bot and they get shareable links..

**Comment by AbirHasan2005** [comment]
https://github.com/AbirHasan2005/PyroFilesStoreBot/blob/9829b9fccf5aaa304ad368ae16928477af0761df/configs.py#L20

Set `OTHER_USERS_CAN_SAVE_FILE` = `True`
