### ISSUE TITLE
Very big issue

### ISSUE THREAD

**Issue by Venomhash123** [AbirHasan2005/PyroFilesStoreBot#31]
Aapka ye bot only plus messenger m hi work kr rha h 

Original telegram pr ye user ko file send nhi kr rha 

Aur na hi ab ye heroku pr deploy ho rhi 
Heroku khta h ki ye code violent ke kaaran deploy nhi hoga

**Comment by AbirHasan2005** [comment]
Heroku flagged this repository 🙂
And it's working on Official Telegram for me. Maybe another problem with your bot. Also working on 3 other tested Telegram unofficial clients.

**Comment by Venomhash123** [comment]
Esi repo ke do bot maine deploy kr rkhe h 
Ek bot to official tg pr response de rha h but dusra nhi 

Us dusre vaale ka maine bot token change bhi kr diya tb bhi vo response nhi de rha to kiya uski repo m kuch problem h

**Comment by AbirHasan2005** [comment]
Bot username?

**Comment by Venomhash123** [comment]
Ha us deploy repo pr dusra new bot banakar jiska username dusra h vo try kiya but vhi paane problem h😑😑😑

**Comment by Venomhash123** [comment]
Aur maine abhi usi bot token ko us dusri repo jo original tg pr work kr rhi thi pr deploy kiya to bot official tg pr work kr rha h 

Yaani ki us phli vaali deploy repo m error h
Jbki dono same repo h

**Comment by Venomhash123** [comment]
Maine us repo ka heroku account transfer krke bhi dekh liya but problem solve nhi hui

**Comment by AbirHasan2005** [comment]
Maybe your repo is outdated 🤔
Jab kam nahi karega tab Heroku se logs save karke send karo idhar, meko dekhna hai.

**Comment by Venomhash123** [comment]
Hy sir maine apne dosto ko ye bot ko start krne ke liye diya jinke paas official tg h to unme se 3 ke official tg pr to response diya baaki 5 ke offical tg pr response nhi diya

**Comment by Venomhash123** [comment]
Log send krta hu

**Comment by Venomhash123** [comment]
Mera heroku account banned ho gya🙄🙄🙄

**Comment by Venomhash123** [comment]
Heroku email ---gillamaanle@ccmail.uk

Password-- Ankur@#$@#123

**Comment by AbirHasan2005** [comment]
Send to [@SorceryBhai](https://t.me/SorceryBhai)

**Comment by Venomhash123** [comment]
Kya send kru 
Jb heroku account hi ban ho gya😶😶😶😶


Aapki repo ko ab heroku pr deploy kaise kru ???????

**Comment by AbirHasan2005** [comment]
Next month deploy patch script ready hoga

**Comment by Venomhash123** [comment]
Ok

**Comment by Venomhash123** [comment]
Ye jo problem aa rhi thi vo telegram ke 64bit me move hone me karan to nhi aa rhi thi???

**Comment by Meet0008** [comment]
![Screenshot_20211221-080903_Chrome](https://user-images.githubusercontent.com/96401257/146861681-b55faf0d-0399-455f-8785-73246598cf5b.jpg)
?

**Comment by Meet0008** [comment]
![20211221_081057](https://user-images.githubusercontent.com/96401257/146861806-ea6dc514-c353-413d-a485-8e8fbb369789.jpg)
?

**Comment by Venomhash123** [comment]
> ![20211221_081057](https://user-images.githubusercontent.com/96401257/146861806-ea6dc514-c353-413d-a485-8e8fbb369789.jpg) ?

Next month new script bnegi

**Comment by Meet0008** [comment]
> > ![20211221_081057](https://user-images.githubusercontent.com/96401257/146861806-ea6dc514-c353-413d-a485-8e8fbb369789.jpg) ?
> 
> Next month new script bnegi

Thanks

**Comment by AbirHasan2005** [comment]
People use this to save copyright materials so Heroku flagged this.
