### ISSUE TITLE
not depolying on heroku 

### ISSUE THREAD

**Issue by priyanshurohilla2004** [AbirHasan2005/PyroFilesStoreBot#41]
![image](https://user-images.githubusercontent.com/64593292/151648295-8055be24-37c6-4bec-a58f-f5ec4ccf6ca3.png)
see nthis

**Comment by dinudre1** [comment]
same error

**Comment by AbirHasan2005** [comment]
Try importing as private and then deploy.

**Comment by Rishwanthpb** [comment]
How to import it as private
